version = 0.1

[format]
input = { s = "str" }
output = "bool"
settings = { in = {}, out = {} }

[[testcases]]
input = { s = "()" }
output = true

[[testcases]]
input = { s = "()[]{}" }
output = true

[[testcases]]
input = { s = "(]" }
output = false

[[testcases]]
input = { s = "([)]" }
output = false

[[testcases]]
input = { s = "{[]}" }
output = true

[[testcases]]
input = { s = "" }
output = true

[[testcases]]
input = { s = "}" }
output = false

[[testcases]]
input = { s = "((()))" }
output = true

[[testcases]]
input = { s = "[" }
output = false
