version = 0.1

[format]
input = { s = "str", t = "str" }
output = "bool"
settings = { in = {}, out = {} }


[[testcases]]
input = { s = "anagram", t = "nagaram" }
output = true

[[testcases]]
input = { s = "rat", t = "car" }
output = false

[[testcases]]
input = { s = "", t = "" }
output = true

[[testcases]]
input = { s = "a", t = "b" }
output = false

[[testcases]]
input = { s = "s", t = "s" }
output = true

[[testcases]]
input = { s = "a", t = "aaa" }
output = false
