version = 1.0

[format]
input.values = { s = "str", t = "str" }
input.settings = {}
output.out = "bool"
output.settings = {}

[[testcases]]
input = { s = "anagram", t = "nagaram" }
output.out = true

[[testcases]]
input = { s = "", t = "" }
output.out = true

[[testcases]]
input = { s = "aaa", t = "aa" }
output.out = false

[[testcases]]
input = { s = "aabaaba", t = "aaababa" }
output.out = true
