version = "0.1"

[format]
input = { tokens = "list[str]" }
output = "int"
settings = { in = {}, out = {} }

[[testcases]]
input = { tokens = ["4", "5", "*"] }
output = 20

[[testcases]]
input = { tokens = ["3", "2", "5", "+", "*"] }
output = 21

[[testcases]]
input = { tokens = ["3", "6", "-", "14", "*"] }
output = -42
